### ISSUE TITLE
how to render_mesh

### ISSUE THREAD

**Issue by zy123456123** [rongakowang/DenseMutualAttention#12]
Hi @rongakowang,

Thanks for sharing the code. How to visualize the results？

**Comment by zy123456123** [comment]
I used render_mesh in your code, but the result was not good.
![Uploading 2024-04-11 20-01-04屏幕截图.png…]()

**Comment by zy123456123** [comment]
I used render_mesh in your code, but the result was not good.
![Uploading 2024-04-11 20-01-04屏幕截图.png…]()

**Comment by rongakowang** [comment]
Hi,

You can extract the predicted vertices and corresponding MANO and object faces to save it as a mesh. All predicted are in the camera frame hence you can directly render the result using external libraries, e.g. pytorch3d or directly view the mesh object.

**Comment by zy123456123** [comment]
Thank you very much for your reply. 
When I use the render_mesh method in your code, the rendering result is not very good.Why are they all rendered white?
![Uploading 2024-04-11 20-01-04屏幕截图.png…]()
![Uploading 图片.png…]()

**Comment by rongakowang** [comment]
Hi,

I believe the render_mesh you refer to are left by the author in the handAR repo (not implemented by us) and has been deprecated. I would suggest saving the hand and object meshes first to visualize. If the image is full white, it might be that the camera parameters are not set correctly.

**Comment by zy123456123** [comment]
ok! Thank you very much for your reply!
