### ISSUE TITLE
Ubantu18.04，Can I run the code

### ISSUE THREAD

**Issue by kyxxc** [rongakowang/DenseMutualAttention#3]
Hello author, I would like to ask if ubantu 18.04 can run your code, and what does the last git+ link mean in the reanme.md

**Comment by rongakowang** [comment]
I haven't tested it myself but I believe it should work, as all dependencies are in Python

I assume you are talking about git+ in requirements.txt, which guides the pip to fetch and install (with `setup.py`) from a git repository.

**Comment by kyxxc** [comment]
Dear Sir
&nbsp; &nbsp; &nbsp; &nbsp;Hello,&nbsp;Thanks for clicking on my question
&nbsp; &nbsp; &nbsp; &nbsp;I would like to ask you some questions about the training code (train.py). I don't see train.py file in the code, may I venture to ask, how is this code trained？Can you share it with me?&nbsp;My email address is ***@***.***
&nbsp; &nbsp; &nbsp; &nbsp;Have a great life, thank you！
&nbsp; &nbsp; &nbsp; &nbsp;
