### ISSUE TITLE
Pretrained checkpoints (HO-3D & DexYCB) do not work

### ISSUE THREAD

**Issue by taeyunwoo** [rongakowang/DenseMutualAttention#5]
Hello, thank you for your works.

I tried to follow up your code with the uploaded pretrained checkpoint of models (HO-3D & DexYCB).
However, I think the checkpoint does not work in my environment.

Actually, I commented out the **neural_renderer** part in [here](https://github.com/rongakowang/DenseMutualAttention/blob/main/main/model_no_render.py#L50). (Also I erase which are related with it.)
However, I think it does not affect the `forward` of the module, if not I apologize for my fault.

As I checked the checkpoints, the 'epoch' of the trained checkpoint is 12, while the paper said you trained 25 epochs.
Also, when I visualize the network output, the hand and object are not reconstructed well.
Significantly, the hand does not look the hand, and the object coordinates far from the hand.

Here is the visualizing result in DexYCB.
![image](https://user-images.githubusercontent.com/59469419/226537766-25232295-e177-4269-8641-35d7323bb227.png)

Thank you for your replying.

**Comment by rongakowang** [comment]
Hi,

Can you please first confirm that you can reproduce the Table 2 results using the weight

The visualization looks to me more like that you are not connecting vertices by the correct faces

**Comment by taeyunwoo** [comment]
In my settings, MJE / MCE / PD = 8.955 / 364.84 / 0.0.
Also, the mesh faces are not wrong, as in vertices visualization below.

![image](https://user-images.githubusercontent.com/59469419/226578073-9c53623a-2346-4c88-9fb0-16002cb70c35.png)

I think, something's wrong in my setting.
Again, I re-examine my setting thoroughly.
