### ISSUE TITLE
About the training code

### ISSUE THREAD

**Issue by kyxxc** [rongakowang/DenseMutualAttention#6]
Dear Sir
       Hello, Thanks for clicking on my question
       I would like to ask you some questions about the training code (train.py). I don't see train.py file in the code, may I venture to ask, how is this code trained？Can you share it with me? My email address is 615975207@qq.com
       Have a great life, thank you！

**Comment by happyiminjay1** [comment]
Hello,

Are you planning to release the training code? 

I want to use it for my research.

Thanks.

**Comment by kyxxc** [comment]
sorry，i dont know






X
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rongakowang/DenseMutualAttention"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月21日(星期二) 晚上9:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rongakowang/DenseMutualAttention] About the training code (Issue #6)





 
Hello,
 
Are you planning to release the training code?
 
I want to use it for my research.
 
Thanks.

**Comment by rongakowang** [comment]
#1
