### ISSUE TITLE
During training, how much do metric values decrease?

### ISSUE THREAD

**Issue by taeyunwoo** [rongakowang/DenseMutualAttention#8]
Hello,
Thank you for your work!

I have researched based on your work, but I wonder 
how much do metric values, such as MME, ADD-S of hand and object, decrease during the training sequence?

In your paper, you trained your network with 25 epochs.
At 25 epochs, can you reply with the metric values of the object and hand?

Thanks.

**Comment by rongakowang** [comment]
Hi,

The provided weights should reflect the metric in the paper, the exact decrease requires retrain the code which I am afraid not having much time to do it.
