### ISSUE TITLE
Different data for DEXYCB test split?

### ISSUE THREAD

**Issue by adwardlee** [rongakowang/DenseMutualAttention#9]
Hi @rongakowang,

Thanks for sharing the code. When I was conducting your code on the evaluation of DEXYCB dataset, the dataset size was only 24K. While in the official s0_test split, there are more than 90K images. What is the difference between your s0_test and official s0_test? Thanks.

**Comment by rongakowang** [comment]
Hi @adwardlee :

Sorry for the late reply, as mentioned in the paper, we follow the the previous work to perform filtering on the test split, you can observe that some samples are not appropriate for the testing, e.g. non-visible hand or object, left hand, no interaction, no labels etc, which is excluded in the testing.
